services:
  db:
    image: postgres:15
    container_name: pixsort_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-image_clustering}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pixsort-network

  rabitmq:
    image: rabbitmq:3-management
    container_name: pixsort_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-password}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pixsort-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  pixsort-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
